In [1]:
#Day1
#Numpy 배열 다루기 2장 p.47~ (20:30 ~ 22:00)

#시스템 마다 64, 32타입은 바뀐다. 
import numpy as np

a = np.arange(5)
a.dtype

dtype('int64')

In [5]:
#배열 형식 출력
a

array([0, 1, 2, 3, 4])

In [4]:
#5개의 원소를 가진 튜플 형태인 것을 확인 가능 / 형상을 출력
a.shape

(5,)

In [7]:
#다차원 배열 생성
m = np.array([np.arange(2), np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [8]:
m.shape

(2, 2)

In [14]:
#Numpy 배열 원소 추출
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [15]:
a[0,0]

1

In [16]:
a[0,1]

2

In [17]:
a[1,0]

3

In [18]:
a[1,1]

4

In [19]:
#Numpy 숫자형
np.float64(42)


42.0

In [20]:
np.int8(42.0)

42

In [21]:
np.bool(42)

True

In [22]:
np.bool(0)

False

In [23]:
np.float(True)

1.0

In [24]:
np.float(False)

0.0

In [25]:
np.arange(7, dtype = np.uint16)

#Tip 복소수는 real(), imag()

array([0, 1, 2, 3, 4, 5, 6], dtype=uint16)

In [26]:
#자료형 객체
a.dtype.itemsize

8

In [27]:
a

array([[1, 2],
       [3, 4]])

In [35]:
#문자코드
c = np.arange(7, dtype='f')
c

array([0., 1., 2., 3., 4., 5., 6.], dtype=float32)

In [34]:
d = np.arange(7, dtype='D')
d

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [36]:
#dtype 생성자 / 부동 소수점 형태 다루기
np.dtype(float)

dtype('float64')

In [37]:
np.dtype('f')

dtype('float32')

In [38]:
np.dtype('d')

dtype('float64')

In [39]:
np.dtype('f8')

dtype('float64')

In [40]:
#축약형태 알 수 있는 코드
np.sctypeDict.keys()

dict_keys(['ushort', 0, 2, 3, 4, 5, 6, 7, 'half', 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 'Float32', 'H', 'uint8', 'q', 'int16', 'D', 'longfloat', 'L', 'longdouble', 1, 'float_', 'uint32', 'f8', 'i1', 'complex128', 'longlong', 8, 'Datetime64', 'int64', 'Int64', 'str', 'F', 'bytes', 'c32', 'uint0', 'float64', 'bool_', 'O', 'intc', 'object', 'Float128', 'Uint64', 'f4', 'l', 'bytes0', 'P', 'int', 'g', 'complex', 'V', 'int0', 'int32', 'unicode_', 'p', 'a', 'c8', 'object0', 'i4', 'Object0', 'csingle', 'timedelta64', 'm8', 'Complex128', 'complex_', 'Void0', 'I', 'intp', 'float16', 'Float64', 'single', 'Bool', 'UInt16', 'G', 'double', 'Complex64', '?', 'uintc', 'f2', 'u1', 'c16', 'uint64', 'f16', 'str_', 'Int32', 'M8', 'bytes_', 'str0', 'datetime64', 'void0', 'i8', 'bool8', 'u4', 'e', 'int_', 'UInt32', 'ulonglong', 'clongdouble', 'b', 'Int8', 'Complex32', 'cdouble', 'd', 'h', 'singlecomplex', 'i2', 'b1', 'float128', 'byte', 'Timedelta64', 'unicode', 'Q', 'int8', 'm', 'compl

In [41]:
#dtype 어트리뷰트
t = np.dtype('Float64')
t.char

/Users/siyeon/.pyenv/versions/3.5.2/lib/python3.5/site-packages/ipykernel_launcher.py:2: DeprecationWarning: Numeric-style type codes are deprecated and will result in an error in the future.
  


'd'

In [42]:
t.type

numpy.float64

In [43]:
t.str

'<f8'

In [46]:
#일차원 슬라이싱 및 인덱싱
a = np.arange(9)
a[3:7]

array([3, 4, 5, 6])

In [47]:
#0~7까지 원소를 2의 배수로 표현
a[:7:2]

array([0, 2, 4, 6])

In [48]:
#거꾸로
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [49]:
#배열 형상 다루기
b = np.arange(24).reshape(2,3,4)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [50]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [55]:
#라블과 플래트의 차이는 지속적으로 조작 유무

b.ravel()
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [57]:
#튜플을 통해 바로 형상 만들기
b.shape = (6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [58]:
#전치(transpose) 행열을 바꾼다.
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [60]:
#크기재지정(resize) 
b.resize((2,12))
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [63]:
#배열 합치기(stacking)
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [65]:
b = 2 * a
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [67]:
#수평 합치기
np.hstack((a,b))


array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [68]:
np.concatenate((a,b), axis = 1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [70]:
#수직 합치기
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [71]:
np.concatenate((a,b), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [72]:
#깊이 우선 합치기(2D 이미지 데이터 쌓기)
np.dstack((a,b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [73]:
#열로 합치기
oned = np.arange(2)
oned

array([0, 1])

In [75]:
twice_oned = 2 * oned
twice_oned

array([0, 2])

In [76]:
np.column_stack((oned, twice_oned))


array([[0, 0],
       [1, 2]])

In [77]:
np.column_stack((a,b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [78]:
#2차원 배열에선 같다. // == 연산자 비교
np.column_stack((a,b)) == np.hstack((a,b))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [79]:
# 행으로 합치기
np.row_stack((oned, twice_oned))

array([[0, 1],
       [0, 2]])

In [80]:
np.row_stack((a, b)) == np.vstack((a,b))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [81]:
#Numpy 배열 쪼개기
#수평
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
np.hsplit(a, 3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [83]:
np.split(a, 3, axis =1)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [91]:
#수직 쪼깨기
np.vsplit(a,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [92]:
np.split(a, 3, axis = 0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [86]:
#깊이 쪼개기
d = np.arange(27).reshape(3,3,3)
d



array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [89]:
np.dsplit(d, 3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

In [3]:
#DAY2 p.67 22:05
import numpy as np
#Numpy 배열 어트리뷰트
b = np.arange(24).reshape(2,12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [4]:
#해당 배열의 차원의 값을 말해줌
b.ndim

2

In [5]:
# 원소의 갯수
b.size

24

In [6]:
#배열 원소의 바이트 수
b.itemsize

8

In [7]:
b.nbytes

192

In [8]:
b.size*b.itemsize

192

In [9]:
#전치 / transpose 함수와 동일한 역할
b.resize(6,4)

In [10]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
b.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [12]:
b.ndim

2

In [13]:
b.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [14]:
#배열의 복소수 경우 허수엔 j 표현
b = np.array([1.j + 1, 2.j+ 3])
b

array([1.+1.j, 3.+2.j])

In [15]:
#실수만 반환
b.real

array([1., 3.])

In [16]:
b.imag 

array([1., 2.])

In [17]:
b.dtype

dtype('complex128')

In [18]:
b.dtype.str

'<c16'

In [19]:
b = np.arange(4).reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [21]:
f = b.flat
f

In [22]:
b.flat[2]

2

In [23]:
b.flat[[1,3]]

array([1, 3])

In [25]:
b.flat = 7
b

array([[7, 7],
       [7, 7]])

In [30]:
#배열 변환하기
b = np.array([1.+1.j, 3.+2.j])
b

array([1.+1.j, 3.+2.j])

In [31]:
#리스트로 변환
b.tolist()

[(1+1j), (3+2j)]

In [32]:
b = np.array([1.+1.j, 3.+2.j])
b

array([1.+1.j, 3.+2.j])

In [33]:
#사용자가 원하는 타입 변경
b.astype(int)

/Users/siyeon/.pyenv/versions/3.5.2/lib/python3.5/site-packages/ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


array([1, 3])

In [45]:
#배열 뷰 생성하고 복사하기 p.73~75 에러 뜸
import scipy.misc
import matplotlib.pyplot as plt

face = scipy.misc.face()
acopy = face.copy()
aview = face.view()
aview.flat = 0

ValueError: array is read-only